import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  AppBar,
  Box,
  CssBaseline,
  Link,
  Stack,
  Toolbar,
  Typography
} from "@mui/material";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900"
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CssBaseline />
      <body>
        <Box sx={{ flexGrow: 1 }}>
          <AppBar position="static">
            <Toolbar>
              <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                Sanqui
              </Typography>
              <Stack direction="row" spacing={2}>
                <Link href="/" underline="hover" color="inherit">
                  Home
                </Link>
                <Link href="/strategies" underline="hover" color="inherit">
                  Strategies
                </Link>
              </Stack>
            </Toolbar>
          </AppBar>
          {children}
        </Box>
      </body>
    </html>
  );
}
